import type { IFs } from "memfs";
import type { GitHubConfig } from "@dapp-forge/blueprint-schema";
import * as path from "path";

interface CreateRepoResult {
  url: string;
  cloneUrl: string;
  prUrl?: string;
}

/** Response fields we need from POST /user/repos */
interface CreatedRepoApi {
  html_url: string;
  clone_url: string;
  owner: { login: string };
  default_branch: string;
}

/**
 * GitHub integration for repository creation and code commits
 * Supports both OAuth tokens (per-user) and App tokens
 */
export class GitHubIntegration {
  private baseUrl = "https://api.github.com";
  private userToken: string | null = null;

  /**
   * Set a user-provided OAuth token (from GitHub OAuth flow)
   */
  setUserToken(token: string): void {
    this.userToken = token;
  }

  /**
   * Get the token to use - prefer user token, fallback to env var
   */
  private getToken(): string {
    // Prefer user's OAuth token (from their session)
    if (this.userToken) {
      return this.userToken;
    }
    // Fallback to environment variable (for server-to-server or testing)
    const token = process.env.GITHUB_TOKEN;
    if (!token) {
      throw new Error(
        "No GitHub token available. Please connect your GitHub account.",
      );
    }
    return token;
  }

  /**
   * Create a new repository and commit generated files
   */
  async createRepository(
    config: GitHubConfig,
    fs: IFs,
    sourcePath: string,
  ): Promise<CreateRepoResult> {
    const token = this.getToken();

    // Create repository
    const repo = await this.createRepo(token, config);

    // Git data API URLs must use the repo owner returned by GitHub. POST /user/repos
    // always creates under the authenticated user; config.owner from the client can be
    // wrong or stale and causes 404 on git/blobs if it does not match.
    const gitConfig = { ...config, owner: repo.ownerLogin };

    // GitHub can return 404 on git/blobs for a short window right after POST /user/repos
    // (replication / git backend readiness). First client attempt often hits this; a reload
    // delays the retry enough that it succeeds — so we wait until the default branch ref exists.
    await this.waitForRepoGitReady(
      token,
      gitConfig.owner,
      gitConfig.repoName,
      repo.defaultBranch,
    );

    // Commit files
    await this.commitFiles(token, gitConfig, fs, sourcePath);

    // Optionally create PR
    let prUrl: string | undefined;
    if (config.createPR) {
      prUrl = await this.createPullRequest(token, gitConfig);
    }

    return {
      url: repo.html_url,
      cloneUrl: repo.clone_url,
      prUrl,
    };
  }

  /**
   * Create a new GitHub repository
   */
  private async createRepo(
    token: string,
    config: GitHubConfig,
  ): Promise<{
    html_url: string;
    clone_url: string;
    ownerLogin: string;
    defaultBranch: string;
  }> {
    const response = await fetch(`${this.baseUrl}/user/repos`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: "application/vnd.github+json",
        "Content-Type": "application/json",
        "X-GitHub-Api-Version": "2022-11-28",
      },
      body: JSON.stringify({
        name: config.repoName,
        description: `Generated by [N]skills`,
        private: config.visibility === "private",
        auto_init: true,
      }),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      console.error("Repo creation failed:", {
        status: response.status,
        statusText: response.statusText,
        error,
        repoName: config.repoName,
        owner: config.owner,
      });

      // Provide user-friendly error messages for common issues
      if (response.status === 422) {
        // Check if repo already exists
        const errorMessage = error.errors?.[0]?.message || error.message || "";
        if (
          errorMessage.toLowerCase().includes("name already exists") ||
          (errorMessage.toLowerCase().includes("repository") &&
            errorMessage.toLowerCase().includes("exists"))
        ) {
          throw new Error(
            `Repository "${config.repoName}" already exists. Please choose a different name.`,
          );
        }
        // Check for invalid repo name
        if (
          errorMessage.toLowerCase().includes("name") &&
          errorMessage.toLowerCase().includes("invalid")
        ) {
          throw new Error(
            `Invalid repository name "${config.repoName}". Repository names can only contain alphanumeric characters, hyphens, underscores, and dots.`,
          );
        }
        throw new Error(
          `Failed to create repository: ${errorMessage || "Repository creation failed. The name might be taken or invalid."}`,
        );
      }

      if (response.status === 401 || response.status === 403) {
        throw new Error(
          "GitHub authentication failed. Please reconnect your GitHub account.",
        );
      }

      throw new Error(
        `Failed to create repository: ${error.message || error.errors?.[0]?.message || response.statusText}`,
      );
    }

    const data = (await response.json()) as CreatedRepoApi;
    const ownerLogin = data.owner?.login ?? config.owner;
    const defaultBranch =
      data.default_branch || config.defaultBranch || "main";
    return {
      html_url: data.html_url,
      clone_url: data.clone_url,
      ownerLogin,
      defaultBranch,
    };
  }

  private sleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  private gitJsonHeaders(token: string): Record<string, string> {
    return {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    };
  }

  /**
   * After creating a repo with auto_init, wait until the default branch ref is readable.
   * Avoids intermittent 404 on git/blobs when the API responds before git data is ready.
   */
  private async waitForRepoGitReady(
    token: string,
    owner: string,
    repo: string,
    branch: string,
    maxWaitMs = 45_000,
  ): Promise<void> {
    const path = `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/ref/heads/${encodeURIComponent(branch)}`;
    const start = Date.now();
    let attempt = 0;

    while (Date.now() - start < maxWaitMs) {
      const res = await fetch(path, {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
      });

      if (res.ok) {
        return;
      }

      if (res.status !== 404) {
        const err = (await res.json().catch(() => ({}))) as { message?: string };
        throw new Error(
          `Repository not ready (${res.status}): ${err.message || res.statusText}`,
        );
      }

      attempt += 1;
      const delay = Math.min(200 * 2 ** Math.min(attempt, 8), 2500);
      await this.sleep(delay);
    }

    throw new Error(
      "GitHub repository was created but the git API did not become ready in time. Please try again.",
    );
  }

  /**
   * POST create blob; retry on 404 while git backend catches up (belt-and-suspenders).
   */
  private async createBlobWithRetry(
    token: string,
    owner: string,
    repo: string,
    base64Content: string,
    relativePath: string,
  ): Promise<{ sha: string }> {
    const url = `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/blobs`;
    const maxAttempts = 8;

    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      const blobResponse = await fetch(url, {
        method: "POST",
        headers: this.gitJsonHeaders(token),
        body: JSON.stringify({
          content: base64Content,
          encoding: "base64",
        }),
      });

      if (blobResponse.ok) {
        return blobResponse.json() as Promise<{ sha: string }>;
      }

      const errorData = (await blobResponse.json().catch(() => ({}))) as {
        message?: string;
      };

      if (blobResponse.status === 404 && attempt < maxAttempts) {
        const delay = Math.min(150 * 2 ** (attempt - 1), 3000);
        console.warn(
          `[GitHub] blob 404 for ${relativePath}, retry ${attempt}/${maxAttempts} in ${delay}ms`,
        );
        await this.sleep(delay);
        continue;
      }

      console.error("Blob creation failed:", {
        file: relativePath,
        status: blobResponse.status,
        error: errorData,
      });
      throw new Error(
        `Failed to create blob for ${relativePath}: ${errorData.message || blobResponse.statusText}`,
      );
    }

    // Unreachable: loop always returns or throws
    throw new Error(`Failed to create blob for ${relativePath}`);
  }

  /**
   * Commit files to repository using Git Data API
   */
  private async commitFiles(
    token: string,
    config: GitHubConfig,
    fs: IFs,
    sourcePath: string,
  ): Promise<void> {
    const owner = config.owner;
    const repo = config.repoName;
    const branch = config.defaultBranch;

    // Get all files
    const files = this.walkDirectory(fs, sourcePath);

    // Create blobs for each file
    const blobs: Array<{ path: string; sha: string }> = [];

    for (const file of files) {
      const content = fs.readFileSync(file);
      const relativePath = path.posix.relative(sourcePath, file);
      const base64 = Buffer.from(content as Buffer).toString("base64");

      const blob = await this.createBlobWithRetry(
        token,
        owner,
        repo,
        base64,
        relativePath,
      );
      blobs.push({ path: relativePath, sha: blob.sha });
    }

    // Create tree
    const treeResponse = await fetch(
      `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/trees`,
      {
        method: "POST",
        headers: this.gitJsonHeaders(token),
        body: JSON.stringify({
          tree: blobs.map((blob) => ({
            path: blob.path,
            mode: "100644",
            type: "blob",
            sha: blob.sha,
          })),
        }),
      },
    );

    if (!treeResponse.ok) {
      throw new Error("Failed to create tree");
    }

    const tree = await treeResponse.json();

    // Create commit
    const commitResponse = await fetch(
      `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/commits`,
      {
        method: "POST",
        headers: this.gitJsonHeaders(token),
        body: JSON.stringify({
          message: "Initial commit from [N]skills",
          tree: tree.sha,
        }),
      },
    );

    if (!commitResponse.ok) {
      throw new Error("Failed to create commit");
    }

    const commit = await commitResponse.json();

    // Create/update reference
    const refResponse = await fetch(
      `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/refs`,
      {
        method: "POST",
        headers: this.gitJsonHeaders(token),
        body: JSON.stringify({
          ref: `refs/heads/${branch}`,
          sha: commit.sha,
        }),
      },
    );

    if (!refResponse.ok) {
      // Try updating existing ref
      await fetch(
        `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/refs/heads/${encodeURIComponent(branch)}`,
        {
          method: "PATCH",
          headers: this.gitJsonHeaders(token),
          body: JSON.stringify({
            sha: commit.sha,
            force: true,
          }),
        },
      );
    }
  }

  /**
   * Create a pull request
   */
  private async createPullRequest(
    token: string,
    config: GitHubConfig,
  ): Promise<string> {
    const owner = config.owner;
    const repo = config.repoName;

    const response = await fetch(
      `${this.baseUrl}/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/pulls`,
      {
        method: "POST",
        headers: this.gitJsonHeaders(token),
        body: JSON.stringify({
          title: config.prTitle || "[N]skills: Generated code",
          body:
            config.prBody || "This PR contains code generated by [N]skills.",
          head: "cradle-generated",
          base: config.defaultBranch,
        }),
      },
    );

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to create PR: ${error.message}`);
    }

    const pr = await response.json();
    return pr.html_url;
  }

  /**
   * Walk directory recursively
   */
  private walkDirectory(fs: IFs, dir: string): string[] {
    const results: string[] = [];

    try {
      const items = fs.readdirSync(dir) as string[];

      for (const item of items) {
        const fullPath = path.posix.join(dir, item);
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
          results.push(...this.walkDirectory(fs, fullPath));
        } else {
          results.push(fullPath);
        }
      }
    } catch {
      // Directory might not exist
    }

    return results;
  }
}
