import type { z } from 'zod';
import type { WalletAuthConfig } from '@dapp-forge/blueprint-schema';
import { dedent } from '@dapp-forge/plugin-sdk';

type Config = z.infer<typeof WalletAuthConfig>;

/**
 * Generate wagmi configuration
 */
export function generateWagmiConfig(config: Config): string {
  return dedent(`
    // Wagmi Configuration
    // Generated by Cradle
    
    import { http, createConfig, createStorage, cookieStorage } from 'wagmi';
    import { arbitrum, arbitrumSepolia, mainnet } from 'wagmi/chains';
    ${config.provider === 'rainbowkit' ? "import { getDefaultConfig } from '@rainbow-me/rainbowkit';" : ''}
    ${config.walletConnectEnabled ? "import { walletConnect, injected, coinbaseWallet } from 'wagmi/connectors';" : "import { injected } from 'wagmi/connectors';"}
    
    const projectId = process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID ?? '';
    
    // Supported chains
    export const supportedChains = [arbitrum, arbitrumSepolia, mainnet] as const;
    
    ${config.provider === 'rainbowkit' ? `
    // RainbowKit configuration
    export const wagmiConfig = getDefaultConfig({
      appName: '${config.appName || 'Cradle App'}',
      projectId,
      chains: supportedChains,
      ssr: true,
      storage: createStorage({
        storage: cookieStorage,
      }),
    });
    ` : `
    // Wagmi configuration
    export const wagmiConfig = createConfig({
      chains: supportedChains,
      connectors: [
        injected(),
        ${config.walletConnectEnabled ? `
        walletConnect({ projectId }),
        coinbaseWallet({ appName: '${config.appName || 'Cradle App'}' }),
        ` : ''}
      ],
      transports: {
        [arbitrum.id]: http(),
        [arbitrumSepolia.id]: http(),
        [mainnet.id]: http(),
      },
      storage: createStorage({
        storage: cookieStorage,
      }),
      ssr: true,
    });
    `}
    
    // Export chain IDs for convenience
    export const ARBITRUM_CHAIN_ID = arbitrum.id;
    export const ARBITRUM_SEPOLIA_CHAIN_ID = arbitrumSepolia.id;
    
    // Default chain
    export const DEFAULT_CHAIN = arbitrum;
  `);
}

/**
 * Generate auth provider component
 */
export function generateAuthProvider(config: Config): string {
  return dedent(`
    // Auth Provider Component
    // Generated by Cradle
    
    'use client';
    
    import { type ReactNode, useState, useEffect } from 'react';
    import { WagmiProvider } from 'wagmi';
    import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
    ${config.provider === 'rainbowkit' ? `
    import { RainbowKitProvider, darkTheme } from '@rainbow-me/rainbowkit';
    import '@rainbow-me/rainbowkit/styles.css';
    ` : ''}
    ${config.siweEnabled ? `
    import { RainbowKitSiweNextAuthProvider } from '@rainbow-me/rainbowkit-siwe-next-auth';
    import { SessionProvider } from 'next-auth/react';
    ` : ''}
    import { wagmiConfig } from '@/lib/auth/wagmi-config';
    
    const queryClient = new QueryClient();
    
    interface AuthProviderProps {
      children: ReactNode;
      ${config.siweEnabled ? 'session?: any;' : ''}
    }
    
    export function AuthProvider({ children${config.siweEnabled ? ', session' : ''} }: AuthProviderProps) {
      const [mounted, setMounted] = useState(false);
      
      useEffect(() => {
        setMounted(true);
      }, []);
      
      return (
        <WagmiProvider config={wagmiConfig}>
          <QueryClientProvider client={queryClient}>
            ${config.siweEnabled ? `
            <SessionProvider session={session}>
              <RainbowKitSiweNextAuthProvider>
            ` : ''}
            ${config.provider === 'rainbowkit' ? `
                <RainbowKitProvider
                  theme={darkTheme({
                    accentColor: '#10b981',
                    accentColorForeground: 'white',
                    borderRadius: 'medium',
                  })}
                  modalSize="compact"
                >
                  {mounted ? children : null}
                </RainbowKitProvider>
            ` : `
                {mounted ? children : null}
            `}
            ${config.siweEnabled ? `
              </RainbowKitSiweNextAuthProvider>
            </SessionProvider>
            ` : ''}
          </QueryClientProvider>
        </WagmiProvider>
      );
    }
    
    export default AuthProvider;
  `);
}

/**
 * Generate connect button component
 */
export function generateConnectButton(config: Config): string {
  if (config.provider === 'rainbowkit') {
    return dedent(`
      // Connect Button Component (RainbowKit)
      // Generated by Cradle
      
      'use client';
      
      import { ConnectButton as RainbowConnectButton } from '@rainbow-me/rainbowkit';
      
      interface ConnectButtonProps {
        className?: string;
        showBalance?: boolean;
        chainStatus?: 'full' | 'icon' | 'name' | 'none';
        accountStatus?: 'full' | 'avatar' | 'address' | 'none';
      }
      
      export function ConnectButton({
        className,
        showBalance = true,
        chainStatus = 'icon',
        accountStatus = 'full',
      }: ConnectButtonProps) {
        return (
          <div className={className}>
            <RainbowConnectButton
              showBalance={showBalance}
              chainStatus={chainStatus}
              accountStatus={accountStatus}
            />
          </div>
        );
      }
      
      /**
       * Custom connect button with full control over rendering
       */
      export function CustomConnectButton({ className }: { className?: string }) {
        return (
          <RainbowConnectButton.Custom>
            {({
              account,
              chain,
              openAccountModal,
              openChainModal,
              openConnectModal,
              mounted,
            }) => {
              const ready = mounted;
              const connected = ready && account && chain;
              
              return (
                <div
                  className={className}
                  {...(!ready && {
                    'aria-hidden': true,
                    style: {
                      opacity: 0,
                      pointerEvents: 'none',
                      userSelect: 'none',
                    },
                  })}
                >
                  {(() => {
                    if (!connected) {
                      return (
                        <button
                          onClick={openConnectModal}
                          className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 
                                   text-white rounded-lg font-medium transition-colors"
                        >
                          Connect Wallet
                        </button>
                      );
                    }
                    
                    if (chain.unsupported) {
                      return (
                        <button
                          onClick={openChainModal}
                          className="px-4 py-2 bg-red-600 hover:bg-red-700 
                                   text-white rounded-lg font-medium transition-colors"
                        >
                          Wrong Network
                        </button>
                      );
                    }
                    
                    return (
                      <div className="flex items-center gap-2">
                        <button
                          onClick={openChainModal}
                          className="flex items-center gap-2 px-3 py-2 bg-zinc-800 
                                   hover:bg-zinc-700 rounded-lg transition-colors"
                        >
                          {chain.hasIcon && (
                            <div
                              className="w-5 h-5 rounded-full overflow-hidden"
                              style={{ background: chain.iconBackground }}
                            >
                              {chain.iconUrl && (
                                <img
                                  alt={chain.name ?? 'Chain icon'}
                                  src={chain.iconUrl}
                                  className="w-5 h-5"
                                />
                              )}
                            </div>
                          )}
                          <span className="text-sm text-white">{chain.name}</span>
                        </button>
                        
                        <button
                          onClick={openAccountModal}
                          className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 
                                   rounded-lg transition-colors"
                        >
                          <span className="text-sm text-white">
                            {account.displayName}
                          </span>
                        </button>
                      </div>
                    );
                  })()}
                </div>
              );
            }}
          </RainbowConnectButton.Custom>
        );
      }
      
      export default ConnectButton;
    `);
  }

  // Custom connect button without RainbowKit
  return dedent(`
    // Connect Button Component
    // Generated by Cradle
    
    'use client';
    
    import { useState } from 'react';
    import { useAccount, useConnect, useDisconnect, useChainId, useSwitchChain } from 'wagmi';
    import { supportedChains, DEFAULT_CHAIN } from '@/lib/auth/wagmi-config';
    
    interface ConnectButtonProps {
      className?: string;
    }
    
    export function ConnectButton({ className }: ConnectButtonProps) {
      const { address, isConnected } = useAccount();
      const { connect, connectors, isPending } = useConnect();
      const { disconnect } = useDisconnect();
      const chainId = useChainId();
      const { switchChain } = useSwitchChain();
      
      const [showConnectors, setShowConnectors] = useState(false);
      const [showChainSelector, setShowChainSelector] = useState(false);
      
      const currentChain = supportedChains.find(c => c.id === chainId);
      const isWrongNetwork = isConnected && !currentChain;
      
      if (!isConnected) {
        return (
          <div className={className + ' relative'}>
            <button
              onClick={() => setShowConnectors(!showConnectors)}
              disabled={isPending}
              className="px-4 py-2 bg-emerald-600 hover:bg-emerald-700 
                       disabled:bg-zinc-700 text-white rounded-lg font-medium 
                       transition-colors"
            >
              {isPending ? 'Connecting...' : 'Connect Wallet'}
            </button>
            
            {showConnectors && (
              <div className="absolute top-full right-0 mt-2 p-2 bg-zinc-900 
                            border border-zinc-700 rounded-lg shadow-xl z-50 min-w-[200px]">
                {connectors.map((connector) => (
                  <button
                    key={connector.uid}
                    onClick={() => {
                      connect({ connector });
                      setShowConnectors(false);
                    }}
                    className="w-full px-3 py-2 text-left text-sm text-white 
                             hover:bg-zinc-800 rounded-md transition-colors"
                  >
                    {connector.name}
                  </button>
                ))}
              </div>
            )}
          </div>
        );
      }
      
      if (isWrongNetwork) {
        return (
          <button
            onClick={() => switchChain?.({ chainId: DEFAULT_CHAIN.id })}
            className={className + ' px-4 py-2 bg-red-600 hover:bg-red-700 text-white rounded-lg font-medium transition-colors'}
          >
            Wrong Network
          </button>
        );
      }
      
      return (
        <div className={className + ' flex items-center gap-2'}>
          <div className="relative">
            <button
              onClick={() => setShowChainSelector(!showChainSelector)}
              className="flex items-center gap-2 px-3 py-2 bg-zinc-800 
                       hover:bg-zinc-700 rounded-lg transition-colors"
            >
              <span className="text-sm text-white">{currentChain?.name}</span>
            </button>
            
            {showChainSelector && (
              <div className="absolute top-full right-0 mt-2 p-2 bg-zinc-900 
                            border border-zinc-700 rounded-lg shadow-xl z-50 min-w-[150px]">
                {supportedChains.map((chain) => (
                  <button
                    key={chain.id}
                    onClick={() => {
                      switchChain?.({ chainId: chain.id });
                      setShowChainSelector(false);
                    }}
                    className={\`w-full px-3 py-2 text-left text-sm text-white 
                             hover:bg-zinc-800 rounded-md transition-colors
                             \${chain.id === chainId ? 'bg-zinc-800' : ''}\`}
                  >
                    {chain.name}
                  </button>
                ))}
              </div>
            )}
          </div>
          
          <button
            onClick={() => disconnect()}
            className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 
                     rounded-lg transition-colors"
          >
            <span className="text-sm text-white font-mono">
              {address?.slice(0, 6)}...{address?.slice(-4)}
            </span>
          </button>
        </div>
      );
    }
    
    export default ConnectButton;
  `);
}

/**
 * Generate auth hooks
 */
export function generateAuthHooks(config: Config): string {
  return dedent(`
    // Authentication Hooks
    // Generated by Cradle
    
    'use client';
    
    import { useAccount, useChainId, useDisconnect, useEnsName, useEnsAvatar } from 'wagmi';
    ${config.siweEnabled ? "import { useSession, signIn, signOut } from 'next-auth/react';" : ''}
    import { supportedChains } from '@/lib/auth/wagmi-config';
    
    export interface UseAuthReturn {
      // Connection state
      address: \`0x\${string}\` | undefined;
      isConnected: boolean;
      isConnecting: boolean;
      isDisconnected: boolean;
      
      // Chain state
      chainId: number | undefined;
      chain: (typeof supportedChains)[number] | undefined;
      isWrongNetwork: boolean;
      
      // ENS
      ensName: string | null | undefined;
      ensAvatar: string | null | undefined;
      
      ${config.siweEnabled ? `
      // Session state (SIWE)
      isAuthenticated: boolean;
      isAuthenticating: boolean;
      session: any;
      ` : ''}
      
      // Actions
      disconnect: () => void;
      ${config.siweEnabled ? `
      signIn: () => Promise<void>;
      signOut: () => Promise<void>;
      ` : ''}
    }
    
    /**
     * Main authentication hook
     */
    export function useAuth(): UseAuthReturn {
      const { address, isConnected, isConnecting, isDisconnected } = useAccount();
      const chainId = useChainId();
      const { disconnect } = useDisconnect();
      const { data: ensName } = useEnsName({ address });
      const { data: ensAvatar } = useEnsAvatar({ name: ensName ?? undefined });
      ${config.siweEnabled ? "const { data: session, status } = useSession();" : ''}
      
      const chain = supportedChains.find(c => c.id === chainId);
      const isWrongNetwork = isConnected && !chain;
      
      ${config.siweEnabled ? `
      const isAuthenticated = status === 'authenticated' && isConnected;
      const isAuthenticating = status === 'loading';
      
      const handleSignIn = async () => {
        await signIn('credentials');
      };
      
      const handleSignOut = async () => {
        await signOut();
        disconnect();
      };
      ` : ''}
      
      return {
        address,
        isConnected,
        isConnecting,
        isDisconnected,
        chainId,
        chain,
        isWrongNetwork,
        ensName,
        ensAvatar,
        ${config.siweEnabled ? `
        isAuthenticated,
        isAuthenticating,
        session,
        signIn: handleSignIn,
        signOut: handleSignOut,
        ` : ''}
        disconnect,
      };
    }
    
    /**
     * Hook to check if user is on a supported chain
     */
    export function useIsOnSupportedChain() {
      const chainId = useChainId();
      return supportedChains.some(c => c.id === chainId);
    }
    
    /**
     * Hook to get the display name (ENS or truncated address)
     */
    export function useDisplayName() {
      const { address } = useAccount();
      const { data: ensName } = useEnsName({ address });
      
      if (ensName) return ensName;
      if (address) return \`\${address.slice(0, 6)}...\${address.slice(-4)}\`;
      return null;
    }
    
    export default useAuth;
  `);
}

/**
 * Generate protected route component
 */
export function generateProtectedRoute(config: Config): string {
  return dedent(`
    // Protected Route Component
    // Generated by Cradle
    
    'use client';
    
    import { type ReactNode } from 'react';
    import { useRouter } from 'next/navigation';
    import { useAuth } from '@/hooks/useAuth';
    
    interface ProtectedRouteProps {
      children: ReactNode;
      fallback?: ReactNode;
      redirectTo?: string;
      requireAuth?: boolean; // Require SIWE authentication
    }
    
    export function ProtectedRoute({
      children,
      fallback,
      redirectTo = '/',
      requireAuth = ${config.siweEnabled ? 'true' : 'false'},
    }: ProtectedRouteProps) {
      const router = useRouter();
      const { isConnected${config.siweEnabled ? ', isAuthenticated, isAuthenticating' : ''} } = useAuth();
      
      ${config.siweEnabled ? `
      // Show loading while checking auth
      if (isAuthenticating) {
        return (
          fallback ?? (
            <div className="flex items-center justify-center min-h-[200px]">
              <div className="animate-spin w-8 h-8 border-2 border-emerald-500 
                            border-t-transparent rounded-full" />
            </div>
          )
        );
      }
      
      // Check authentication
      const hasAccess = requireAuth ? isAuthenticated : isConnected;
      ` : `
      const hasAccess = isConnected;
      `}
      
      if (!hasAccess) {
        if (redirectTo) {
          router.push(redirectTo);
          return null;
        }
        
        return (
          fallback ?? (
            <div className="flex flex-col items-center justify-center min-h-[200px] gap-4">
              <p className="text-zinc-400">
                ${config.siweEnabled ? 'Please connect and sign in to access this page' : 'Please connect your wallet to access this page'}
              </p>
            </div>
          )
        );
      }
      
      return <>{children}</>;
    }
    
    export default ProtectedRoute;
  `);
}

